redis.host=redis
redis.port=6379
redis.new.max-items=10000
hbase.enabled=true
hbase.zookeeper.quorum=zookeeper-1,zookeeper-2,zookeeper-3
hbase.zookeeper.znode.parent=/hbase
hbase.table.prefix=openrec_
hive.enabled=true
kafka.servers=kafka-1:9092,kafka-2:9092,kafka-3:9092
kafka.item.topic=item
kafka.user.topic=user
kafka.event.topic=event
kafka.groupId=openrec-feature-spark
hdfs.output=hdfs://namenode:8020/openrec
checkpoint.path=hdfs://namenode:8020/openrec/checkpoints/spark-features
spark.master=spark://spark-master:7077
